source .zprofile after installing homebrew, prompt user before installing brews, and change tabs to spaces

diff --git a/configuratio_maculus b/configuratio_maculus
--- a/configuratio_maculus
+++ b/configuratio_maculus
@@ -13,11 +13,11 @@ set -e
 ###############################################################################
 
 if [ -e functions ]; then
-	cd "$(dirname "${BASH_SOURCE[0]}")" \
-		&& . "functions"
+  cd "$(dirname "${BASH_SOURCE[0]}")" \
+    && . "functions"
 else
-	printf "\n ⚠️  ./functions not found\n"
-	exit 1
+  printf "\n ⚠️  ./functions not found\n"
+  exit 1
 fi
 
 ###############################################################################
@@ -78,24 +78,24 @@ chapter "Installing Dependencies…"
 # XCode
 # -----------------------------------------------------------------------------
 if type xcode-select >/dev/null 2>&1 && xpath=$( xcode-select --print-path ) &&
-	test -d "${xpath}" && test -x "${xpath}" ; then
-	print_success_muted "Xcode already installed. Skipping."
+  test -d "${xpath}" && test -x "${xpath}" ; then
+  print_success_muted "Xcode already installed. Skipping."
 else
-	step "Installing Xcode…"
-	xcode-select --install
+  step "Installing Xcode…"
+  xcode-select --install
   read -p "   ✦  Press enter to continue…"
-	print_success "Xcode installed!"
+  print_success "Xcode installed!"
 fi
 
 if [ ! -d "$HOME/.bin/" ]; then
-	mkdir "$HOME/.bin"
+  mkdir "$HOME/.bin"
 fi
 
 # -----------------------------------------------------------------------------
 # Homebrew
 # -----------------------------------------------------------------------------
 if ! [ -x "$(command -v brew)" ]; then
-	step "Installing Homebrew…"
+  step "Installing Homebrew…"
   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
 
   case $(uname -m) in
@@ -114,29 +114,32 @@ if ! [ -x "$(command -v brew)" ]; then
   # the homebrew path so as to enable dynamic installation on either arm or x86 systems
 
   (echo; echo "eval \"\$(${homebrew_path}/bin/brew shellenv)\"") >> $HOME/.zprofile
-  eval "\$(${homebrew_path}/bin/brew shellenv)"
+  # eval "\$(${homebrew_path}/bin/brew shellenv)"
+  source $HOME/.zprofile
 
-	print_success "Homebrew installed!"
+  print_success "Homebrew installed!"
 else
-	print_success_muted "Homebrew already installed. Skipping."
+  print_success_muted "Homebrew already installed. Skipping."
 fi
 
 if brew list | grep -Fq brew-cask; then
-	step "Uninstalling old Homebrew-Cask…"
-	brew uninstall --force brew-cask
-	print_success "Homebrew-Cask uninstalled!"
+  step "Uninstalling old Homebrew-Cask…"
+  brew uninstall --force brew-cask
+  print_success "Homebrew-Cask uninstalled!"
 fi
 
 ###############################################################################
 # INSTALL: brews
 ###############################################################################
 if [ -e $cwd/installs/brews ]; then
-	chapter "Installing Homebrew formulae…"
-
-
-	for brew in $(<$cwd/installs/brews); do
-		install_brews $brew
-	done
+  if ask "Do you want to install brews?" Y; then
+    chapter "Installing Homebrew formulae…"
+    for brew in $(<$cwd/installs/brews); do
+      install_brews $brew
+    done
+  else
+    print_success_muted "Declined to install brews. Skipped.";
+  fi
 fi
 
 ###############################################################################
@@ -151,13 +154,13 @@ brew update
 if [ -e $cwd/installs/casks ]; then
 
   if ask "Do you want to install casks?" Y; then
-  	chapter "Installing apps via Homebrew…"
+    chapter "Installing apps via Homebrew…"
     brew tap homebrew/cask-fonts
-  	for cask in $(<$cwd/installs/casks); do
-  	    install_application_via_brew $cask
-  	done
+    for cask in $(<$cwd/installs/casks); do
+      install_application_via_brew $cask
+    done
   else
-    print_success_muted "Declined to install dotfiles. Skipped.";
+    print_success_muted "Declined to install casks. Skipped.";
   fi
 
 fi
@@ -168,22 +171,22 @@ fi
 chapter "Installing apps from App Store…"
 if [ -x mas ]; then
 
-	print_warning "Please install mas-cli first: brew mas. Skipping."
+  print_warning "Please install mas-cli first: brew mas. Skipping."
 
-	else
+  else
 
-	if [ -e $cwd/installs/apps ]; then
+  if [ -e $cwd/installs/apps ]; then
     # The account command is not supported as of macOS 12, skip that check
     # https://github.com/mas-cli/mas#known-issues
 
-		# Workaround for associative array in Bash 3
-		# https://stackoverflow.com/questions/6047648/bash-4-associative-arrays-error-declare-a-invalid-option
-		for app in $(<$cwd/installs/apps); do
-			KEY="${app%%::*}"
-			VALUE="${app##*::}"
-			install_application_via_app_store $KEY $VALUE
-		done
-	fi
+    # Workaround for associative array in Bash 3
+    # https://stackoverflow.com/questions/6047648/bash-4-associative-arrays-error-declare-a-invalid-option
+    for app in $(<$cwd/installs/apps); do
+      KEY="${app%%::*}"
+      VALUE="${app##*::}"
+      install_application_via_app_store $KEY $VALUE
+    done
+  fi
 
 fi
 
@@ -199,9 +202,9 @@ brew cleanup 2> /dev/null
 chapter "Running customizations…"
 
 if [ -f "$cwd/customizations" ]; then
-	. "$cwd/customizations"; printf "\n  Performing customizations…";
+  . "$cwd/customizations"; printf "\n  Performing customizations…";
 else
-	print_warning "No customizations found. Skipping."
+  print_warning "No customizations found. Skipping."
 fi
 
 ###############################################################################
