update readme, change filenames, add mac script, tweak scripts

diff --git a/configuratio b/configuratio
--- a/configuratio
+++ b/configuratio
@@ -12,11 +12,11 @@ set -e
 # TWIRL: Check for required functions file
 ###############################################################################
 
-if [ -e twirl ]; then
+if [ -e utils ]; then
 	cd "$(dirname "${BASH_SOURCE[0]}")" \
-		&& . "twirl"
+		&& . "utils"
 else
-	printf "\n ⚠️  ./twirl not found  💃🏾 First, you need to twirl on your haters\n"
+	printf "\n ⚠️  ./utils not found\n"
 	exit 1
 fi
 
@@ -31,20 +31,21 @@ check_bash_version
 ###############################################################################
 
 printf "
-   _
-  | |
-  | |  __   ,_    _  _  _    __, _|_ 🍋  __   _  _
-  |/  /  \_/  |  / |/ |/ |  /  |  |  |  /  \_/ |/ |
-  |__/\__/    |_/  |  |  |_/\_/|_/|_/|_/\__/   |  |
-  |\  ---------------------------------------------
-  |/  Cause you slay           [for Bash 3.2 - 3.9]
-╭───────────────────────────────────────────────────╮
-│  Okay developers now let's get in ${bold}formation${normal}.      │
-│───────────────────────────────────────────────────│
-│  Safe to run multiple times on the same machine.  │
-│  It ${green}installs${reset}, ${blue}upgrades${reset}, or ${yellow}skips${reset} packages based   │
-│  on what is already installed on the machine.     │
-╰───────────────────────────────────────────────────╯
+
+.------..------..------..------..------..------..------..------.
+|W.--. ||I.--. ||Z.--. ||A.--. ||R.--. ||D.--. ||R.--. ||Y.--. |
+| :/\: || (\/) || :(): || (\/) || :(): || :/\: || :(): || (\/) |
+| :\/: || :\/: || ()() || :\/: || ()() || (__) || ()() || :\/: |
+| '--'W|| '--'I|| '--'Z|| '--'A|| '--'R|| '--'D|| '--'R|| '--'Y|
+`------'`------'`------'`------'`------'`------'`------'`------'
+╭─────────────────────────────────────────────────────╮
+│  A great and powerful script for configuring macOS  │
+│  (Forked from ${bold}github.com/minamarkham/formation${reset})     │
+│─────────────────────────────────────────────────────│
+│  Safe to run multiple times on the same machine.    │
+│  It ${green}installs${reset}, ${blue}upgrades${reset}, or ${yellow}skips${reset} packages based     │
+│  on what is already installed on the machine.       │
+╰─────────────────────────────────────────────────────╯
    ${dim}$(get_os) $(get_os_version) ${normal} // ${dim}$BASH ${normal} // ${dim}$BASH_VERSION${reset}
 "
 
@@ -88,18 +89,6 @@ if [ ! -d "$HOME/.bin/" ]; then
 fi
 
 # -----------------------------------------------------------------------------
-# Bash-it (COMMENTING OUT FOR NOW [ZSH])
-# -----------------------------------------------------------------------------
-# if [ -d "$HOME/.bash_it" ]; then
-# 	print_success_muted "Bash-it already installed. Skipping."
-# else
-# 	step "Installing Bash-it…"
-# 	git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it
-# 	~/.bash_it/install.sh --silent --no-modify-config
-# 	print_success "Bash-it installed!"
-# fi
-# 
-# -----------------------------------------------------------------------------
 # NVM
 # -----------------------------------------------------------------------------
 if [ -x nvm ]; then
@@ -137,10 +126,10 @@ fi
 ###############################################################################
 # INSTALL: brews
 ###############################################################################
-if [ -e $cwd/swag/brews ]; then
+if [ -e $cwd/installs/brews ]; then
 	chapter "Installing Homebrew formulae…"
 
-	for brew in $(<$cwd/swag/brews); do
+	for brew in $(<$cwd/installs/brews); do
 		install_brews $brew
 	done
 fi
@@ -154,10 +143,10 @@ brew update
 ###############################################################################
 # INSTALL: casks
 ###############################################################################
-if [ -e $cwd/swag/casks ]; then
+if [ -e $cwd/installs/casks ]; then
 	chapter "Installing apps via Homebrew…"
 
-	for cask in $(<$cwd/swag/casks); do
+	for cask in $(<$cwd/installs/casks); do
 	    install_application_via_brew $cask
 	done
 fi
@@ -172,11 +161,11 @@ if [ -x mas ]; then
 
 	else
 
-	if [ -e $cwd/swag/apps ]; then
+	if [ -e $cwd/installs/apps ]; then
 		if mas_setup; then
 			# Workaround for associative array in Bash 3
 			# https://stackoverflow.com/questions/6047648/bash-4-associative-arrays-error-declare-a-invalid-option
-			for app in $(<$cwd/swag/apps); do
+			for app in $(<$cwd/installs/apps); do
 				KEY="${app%%::*}"
 				VALUE="${app##*::}"
 				install_application_via_app_store $KEY $VALUE
@@ -197,10 +186,10 @@ brew cleanup 2> /dev/null
 ###############################################################################
 # INSTALL: npm packages
 ###############################################################################
-if [ -e $cwd/swag/npm ]; then
+if [ -e $cwd/installs/npm ]; then
 	chapter "Installing npm packages…"
 
-	for pkg in $(<$cwd/swag/npm); do
+	for pkg in $(<$cwd/installs/npm); do
 		KEY="${pkg%%::*}"
 		VALUE="${pkg##*::}"
 		install_npm_packages $KEY $VALUE
@@ -211,18 +200,27 @@ fi
 ###############################################################################
 # OPTIONAL: Customizations
 ###############################################################################
-chapter "Adding hot sauce…"
-if [ -f "$HOME/.hot-sauce" ]; then
-	if ask "Do you want to add hot sauce?" Y; then
-		. "$HOME/.hot-sauce"; printf "\n  You got hot sauce in your bag. 🔥 ${bold}Swag.${normal}\n";
-	else
-		print_success_muted "Hot sauce declined. Skipped.";
-	fi
+chapter "Performing additional setup…"
+
+if ask "Do you want to setup dotfiles right now?" Y; then
+  clone_dotfiles
+  printf "\n  Setting up dotfiles…\n"
+  . "$HOME/.dotfiles/setup_dotfiles"
 else
-	print_warning "No ~/.hot-sauce found. Skipping."
+  print_success_muted "Declined to setup dotfiles. Skipped.";
+fi
+if [ -e "$cwd/macos"]
+  if ask "Do you want to set up macOS defaults?" Y; then
+    printf "\n  Setting up macOS defaults…\n"
+    . "$cwd/macos"; printf
+  else
+    print_success_muted "Declined to setup macOS defaults. Skipped.";
+  fi
+else
+  print_warning "No macOS setup script found\! Skipping."
 fi
 
 ###############################################################################
-# 🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋
+# NOTIFY COMPLETED
 ###############################################################################
-e_lemon_ated
+completed
